version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./Backend
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  client:
    build: ./frontend
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data: